package models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

// Generated Jun 1, 2022, 2:02:09 PM by Hibernate Tools 5.4.33.Final

/**
 * Articlesstock generated by hbm2java
 */
@Entity
public class Articlesstock implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer codeArt;
	@Column
	private int qteArt;
	@Column
	private String nomArt;
	@Column
	private String descArt;
	@Column
	private int prixArt;

	public Articlesstock() {
	}

	public Articlesstock(int qteArt, String nomArt, String descArt, int prixArt) {
		this.qteArt = qteArt;
		this.nomArt = nomArt;
		this.descArt = descArt;
		this.prixArt = prixArt;
	}

	public Integer getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(Integer codeArt) {
		this.codeArt = codeArt;
	}

	public int getQteArt() {
		return this.qteArt;
	}

	public void setQteArt(int qteArt) {
		this.qteArt = qteArt;
	}

	public String getNomArt() {
		return this.nomArt;
	}

	public void setNomArt(String nomArt) {
		this.nomArt = nomArt;
	}

	public String getDescArt() {
		return this.descArt;
	}

	public void setDescArt(String descArt) {
		this.descArt = descArt;
	}

	public int getPrixArt() {
		return this.prixArt;
	}

	public void setPrixArt(int prixArt) {
		this.prixArt = prixArt;
	}

}
