package models;
// Generated Jun 1, 2022, 2:02:09 PM by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * ArticlesApprovisionnement generated by hbm2java
 */
public class ArticlesApprovisionnement implements java.io.Serializable {

	private int codeArt;
	private int qteCommande;
	private Date datePrevueLivraison;

	public ArticlesApprovisionnement() {
	}

	public ArticlesApprovisionnement(int codeArt, int qteCommande, Date datePrevueLivraison) {
		this.codeArt = codeArt;
		this.qteCommande = qteCommande;
		this.datePrevueLivraison = datePrevueLivraison;
	}

	public int getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(int codeArt) {
		this.codeArt = codeArt;
	}

	public int getQteCommande() {
		return this.qteCommande;
	}

	public void setQteCommande(int qteCommande) {
		this.qteCommande = qteCommande;
	}

	public Date getDatePrevueLivraison() {
		return this.datePrevueLivraison;
	}

	public void setDatePrevueLivraison(Date datePrevueLivraison) {
		this.datePrevueLivraison = datePrevueLivraison;
	}

}
