package models;
// Generated Jun 1, 2022, 2:02:09 PM by Hibernate Tools 5.4.33.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Clients generated by hbm2java
 */
@Entity
public class Clients implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer codeClient;
	@Column
	private String nameClient;
	@Column
	private String emailClient;
	@Column
	private String addressClient;
	@Column
	private String telClient;

	public Clients() {
	}

	public Clients(String nameClient, String emailClient, String addressClient, String telClient) {
		this.nameClient = nameClient;
		this.emailClient = emailClient;
		this.addressClient = addressClient;
		this.telClient = telClient;
	}

	public Integer getCodeClient() {
		return this.codeClient;
	}

	public void setCodeClient(Integer codeClient) {
		this.codeClient = codeClient;
	}

	public String getNameClient() {
		return this.nameClient;
	}

	public void setNameClient(String nameClient) {
		this.nameClient = nameClient;
	}

	public String getEmailClient() {
		return this.emailClient;
	}

	public void setEmailClient(String emailClient) {
		this.emailClient = emailClient;
	}

	public String getAddressClient() {
		return this.addressClient;
	}

	public void setAddressClient(String addressClient) {
		this.addressClient = addressClient;
	}

	public String getTelClient() {
		return this.telClient;
	}

	public void setTelClient(String telClient) {
		this.telClient = telClient;
	}

}
